version: '3.0'
services:
  macchina-edge-ce:
    image: "macchina/edge-ce:ubuntu"
    build: .
    ports:
      - 22080:22080
    volumes:
      - logvolume:/opt/macchina/var/log
      - datavolume:/opt/macchina/var/lib

volumes:
    logvolume:
    datavolume:
